language: python
python:
  - "2.7"
  - "3.5"
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - cmake
script:
  - python setup.py install # --qmake=/path/to/bin/qmake --cmake=/path/to/bin/cmake --openssl=/path/to/openssl/bin
