language: python
dist: trusty
python:
  - "2.7"
  - "3.5"
addons:
  apt:
    #sources:
    #- george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
before_install:
   - sudo add-apt-repository ppa:beineri/opt-qt551 -y
   - sudo apt-get update
install:
  ##- sudo apt-get install qt5-default libqt5xmlpatterns5-dev -y
  - sudo apt-get install qt55-meta -y
script:
  - python setup.py install # --qmake=/path/to/bin/qmake --cmake=/path/to/bin/cmake --openssl=/path/to/openssl/bin
