language: python
python:
  - "2.7"
  - "3.5"
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - debian-sid
    packages:
    - cmake
    - cmake-data
    - qt5-default
script:
  - python setup.py install # --qmake=/path/to/bin/qmake --cmake=/path/to/bin/cmake --openssl=/path/to/openssl/bin
